### ISSUE TITLE
general question about your experience building this project

### ISSUE THREAD

**Issue by ghost** [yash-ahir/passman-flutter#4]
Hi @yash-ahir  ,

Hope you are all well !

I would like to create a clone of [teampass](https://github.com/nilsteampassnet/TeamPass) a collaborative password manager, and I was wondering if you knew or can explain how to create a catalog of items, organised with an [animated tree view](https://github.com/embraceitmobile/animated_tree_view), and [flutter_rbac](https://github.com/wilpar/flutter_rbac) for managing roles and permissions. From your experience, what advices would you give me for neat architecture.

Thanks for any insights or inputs on that question.

teampass screeenshot:
![pf_tp_5](https://user-images.githubusercontent.com/1963546/143676762-88e5e5c0-6a3e-473f-adae-09d9ae274f18.png)

Cheers,
Luc

**Comment by yash-ahir** [comment]
> Hi @yash-ahir  ,
> 
> Hope you are all well !
> 
> I would like to create a clone of [teampass](https://github.com/nilsteampassnet/TeamPass) a collaborative password manager, and I was wondering if you knew or can explain how to create a catalog of items, organised with an [animated tree view](https://github.com/embraceitmobile/animated_tree_view), and [flutter_rbac](https://github.com/wilpar/flutter_rbac) for managing roles and permissions. From your experience, what advices would you give me for neat architecture.
> 
> Thanks for any insights or inputs on that question.
> 
> teampass screeenshot:
> ![pf_tp_5](https://user-images.githubusercontent.com/1963546/143676762-88e5e5c0-6a3e-473f-adae-09d9ae274f18.png)
> 
> Cheers,
> Luc

Hey Luc,

Well it pains to say but you've kind of asked the wrong person about this, I neither have any experience with the tree view you mentioned, nor the role management library. Although I think I might be able to steer you in the right direction, try asking around on the Discord community [here](https://discord.com/invite/N7Yshp4). They're usually very helpful and extremely active aswell.
